pod 'AFNetworking'
pod 'Mantle', '~> 1.5.4'
pod 'BDBOAuth1Manager'
pod 'FXForms'
pod 'SVProgressHUD'
pod 'SVPullToRefresh'
pod 'DTCoreText'
pod 'VGParallaxHeader'
pod 'iOS-KML-Framework'
pod 'CRGradientNavigationBar'
pod 'TSMessages'
#pod 'YLProgressBar'
#pod 'Simple-KML'
#pod 'UIImage+SpriteAdditions'
#pod 'CFCountryFlags'
